In [1]:
import pandas as pd
wine=pd.read_csv('https://bit.ly/wine_csv_data')
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6497 entries, 0 to 6496
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   alcohol  6497 non-null   float64
 1   sugar    6497 non-null   float64
 2   pH       6497 non-null   float64
 3   class    6497 non-null   float64
dtypes: float64(4)
memory usage: 203.2 KB


In [2]:
data=wine[['alcohol','sugar','pH']].to_numpy()
target=wine['class'].to_numpy()

In [3]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(data, 
                                                                      target, 
                                                                      test_size=0.2, 
                                                                      random_state=42)

In [4]:
sub_input, val_input, sub_target, val_target = train_test_split(train_input,
                                                               train_target,
                                                               test_size=0.2,
                                                               random_state=42)

In [5]:
sub_input.shape

(4157, 3)

In [6]:
val_input.shape

(1040, 3)

In [7]:
test_input.shape

(1300, 3)

In [8]:
from sklearn.tree import DecisionTreeClassifier
dt=DecisionTreeClassifier(random_state=42)
dt.fit(sub_input, sub_target)
dt.score(sub_input, sub_target)

0.9971133028626413

In [9]:
dt.score(val_input, val_target)

0.864423076923077

In [10]:
from sklearn.model_selection import cross_validate
scores = cross_validate(dt, train_input, train_target)
scores

{'fit_time': array([0.0041101 , 0.00417995, 0.0045681 , 0.00409698, 0.00389504]),
 'score_time': array([0.00028682, 0.00032735, 0.00028014, 0.00026393, 0.00025296]),
 'test_score': array([0.86923077, 0.84615385, 0.87680462, 0.84889317, 0.83541867])}

In [11]:
import numpy as np
np.mean(scores['test_score'])

0.855300214703487

In [12]:
from sklearn.model_selection import StratifiedKFold

scores=cross_validate(dt, train_input, train_target, cv=StratifiedKFold())
np.mean(scores['test_score'])

0.855300214703487

In [13]:
splitter = StratifiedKFold(n_splits=10, shuffle=True, random_state=42)

scores=cross_validate(dt, train_input, train_target, cv=splitter)
np.mean(scores['test_score'])

0.8574181117533719

In [14]:
from sklearn.model_selection import GridSearchCV

params={'min_impurity_decrease':[0.0001, 0.0002, 0.0003, 0.0004, 0.0005]}

In [15]:
gs=GridSearchCV(DecisionTreeClassifier(random_state=42), params, n_jobs=-1)

In [16]:
gs.fit(train_input, train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'min_impurity_decrease': [0.0001, 0.0002, 0.0003,
                                                   0.0004, 0.0005]})

In [17]:
dt=gs.best_estimator_

In [18]:
dt.score(train_input, train_target)

0.9615162593804117

In [19]:
gs.best_params_

{'min_impurity_decrease': 0.0001}

In [21]:
gs.cv_results_['mean_test_score']

array([0.86819297, 0.86453617, 0.86492226, 0.86780891, 0.86761605])

In [23]:
best_index=np.argmax(gs.cv_results_['mean_test_score'])
gs.cv_results_['params'][best_index]

{'min_impurity_decrease': 0.0001}

In [29]:
params={'min_impurity_decrease':np.arange(0.0001, 0.001, 0.0001), 
        'max_depth':range(5,20,1),
        'min_samples_split':range(2,100,10)}
            


In [33]:
gs=GridSearchCV(DecisionTreeClassifier(random_state=42),params,n_jobs=-1)
gs.fit(train_input,train_target)

GridSearchCV(estimator=DecisionTreeClassifier(random_state=42), n_jobs=-1,
             param_grid={'max_depth': range(5, 20),
                         'min_impurity_decrease': array([0.0001, 0.0002, 0.0003, 0.0004, 0.0005, 0.0006, 0.0007, 0.0008,
       0.0009]),
                         'min_samples_split': range(2, 100, 10)})

In [34]:
gs.best_params_

{'max_depth': 14, 'min_impurity_decrease': 0.0004, 'min_samples_split': 12}

In [35]:
np.max(gs.cv_results_['mean_test_score'])

0.8683865773302731

In [36]:
from scipy.stats import uniform, randint

In [37]:
rgen = randint(0,10)
rgen.rvs(10)

array([2, 5, 7, 8, 6, 7, 4, 7, 9, 8])

In [40]:
np.unique(rgen.rvs(1000), return_counts=True)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([ 93,  81, 106, 115, 106, 108, 113,  82,  99,  97]))

In [41]:
ugen = uniform(0,1)
ugen.rvs(10)

array([0.82458687, 0.20415929, 0.53926771, 0.10339659, 0.4986295 ,
       0.60615386, 0.66343999, 0.86271674, 0.35802324, 0.0549315 ])

In [ ]:
params={'min_iimpurity_decrease':uniform(0.0001, 0.001),
       'max_depth'}